apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: rule1
  project: giri-test-labels
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/rule1/cluster-wide-rule.yaml
    options: {}
    type: Yaml
  version: rule1-version1
