apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: addon-ns1
  project: giri-test-labels
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mks-labels
  resourceQuotas: {}
