apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: cilium-test
  project: giri-test-labels
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-aks-testing
    - key: rafay.dev/clusterName
      value: giri-mks-canal
  resourceQuotas: {}
