apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: istio-system
  project: giri-test-labels
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-qc-labels
    - key: rafay.dev/clusterName
      value: giri-qc-eks
    - key: rafay.dev/clusterName
      value: giri-qc-aks
    - key: rafay.dev/clusterName
      value: giri-import-aks
    - key: rafay.dev/clusterName
      value: giri-aks-1-23-8
  resourceQuotas: {}
