apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: mysql
  project: giri-test-labels
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-aks
    - key: rafay.dev/clusterName
      value: giri-microk8s-imported
  resourceQuotas: {}
