apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: new-repo-1
  project: giri-test-labels
spec:
  agents:
  - {}
  credentials:
    password: sealed://credentials.password
    username: rakshith@rafay.co
  endpoint: https://github.com/rakshith-rafay/prod-test-repo.git
  secret:
    name: file://artifacts/new-repo-1/sealed-secret.yaml
  sharing: {}
  type: Git
