apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: am-custom-3
  project: giri-test-labels
spec:
  base:
    name: default
    version: 1.22.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  type: custom
  version: v4
