apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: dec-storage
  project: giri-test-labels
spec:
  base:
    name: default
    version: 1.22.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableRookCeph: true
  type: custom
  version: v1
