apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: labels-bp
  project: giri-test-labels
spec:
  base:
    name: default
    version: 1.22.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  opaPolicy:
    opaPolicy:
    - name: policy-restricted
      version: version-1672854643
    profile:
      name: default
      version: latest
  type: custom
  version: v2
